-- Migration: create_works
-- 2026-08-17
-- 说明：此前 works 表是在 CloudBase 控制台手工建的，仓库里缺「建表菜谱」，
--       导致环境无法从零复现。本文件把建表语句补进 migrations，使数据库结构可版本化、可重建。
-- 字段与线上实例保持一致（来源：information_schema.columns 核对）。

CREATE TABLE IF NOT EXISTS works (
  id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        text        NOT NULL,
  author       text,
  original_url text        NOT NULL,
  links        jsonb       DEFAULT '[]'::jsonb,
  cover_url    text,
  summary      text,
  category     text,
  tags         jsonb       DEFAULT '[]'::jsonb,
  status       smallint    DEFAULT 1,   -- DEPRECATED: 审核设计已移除，前端不再读写；保留仅为向后兼容
  created_at   timestamptz DEFAULT now(),
  author_uid   text
);

-- 开启行级安全（RLS）。细粒度读写策略由后续 migration（20260817192100_*）定义。
ALTER TABLE works ENABLE ROW LEVEL SECURITY;
